//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReservation.DataModel.dbmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieReserve
    {
        public int Id { get; set; }
        public Nullable<int> MovieId { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> SeatId { get; set; }
        public Nullable<int> ReservationStatusId { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<System.DateTime> MovieSchedule { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual ReservationStatu ReservationStatu { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
