//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReservation.DataModel.dbmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieSeatReservationDBEntities : DbContext
    {
        public MovieSeatReservationDBEntities()
            : base("name=MovieSeatReservationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<MovieReserve> MovieReserves { get; set; }
        public virtual DbSet<MovieSchedule> MovieSchedules { get; set; }
        public virtual DbSet<ReservationStatu> ReservationStatus { get; set; }
        public virtual DbSet<SeatAvailabilityPerSched> SeatAvailabilityPerScheds { get; set; }
        public virtual DbSet<Seat> Seats { get; set; }
    }
}
