//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReservation.DataModel.dbmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seat()
        {
            this.MovieReserves = new HashSet<MovieReserve>();
            this.SeatAvailabilityPerScheds = new HashSet<SeatAvailabilityPerSched>();
        }
    
        public int Id { get; set; }
        public string SeatNumber { get; set; }
        public Nullable<int> SeatRow { get; set; }
        public Nullable<int> SeatColumn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieReserve> MovieReserves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatAvailabilityPerSched> SeatAvailabilityPerScheds { get; set; }
    }
}
