//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReservation.DataModel.dbmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatAvailabilityPerSched
    {
        public int Id { get; set; }
        public Nullable<int> SeatId { get; set; }
        public Nullable<int> MovieScheduleId { get; set; }
        public Nullable<bool> IsSeatAvailable { get; set; }
    
        public virtual MovieSchedule MovieSchedule { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
